### ISSUE TITLE
Single User to Multiple Users

### ISSUE THREAD

**Issue by NityaNagaSai** [csc510fall23g45/slash#14]
We can multiple users for the full version. Implement the functionality for the feature.

**Comment by sairajzero** [comment]
I have added support for multi-users in [here](https://github.com/csc510fall23g45/slash/commit/4d6cf230d1d4ee8c382480a255dee2e85b23d11a). The data files are stored in separate file paths for each username so that each user can have their own set of wishlists and wishlisted items. In full version, users can any number of wishlists
